### ISSUE TITLE
CyanogenMod 13 Alpha release

### ISSUE THREAD

**Issue by lukepaulkopera** [XePeleato/android_device_huawei_p8lite_alel21#12]
Hi I want to flash it with TWRP but i get Error Status 7. I tried to fix it but it did not. Help, thanks :)

**Comment by powerpaul17** [comment]
Have you wiped the data partition? It was necessary to do so first.

**Comment by lukepaulkopera** [comment]
now it works thanks :)

**Comment by lukepaulkopera** [comment]
now it stuck on starting apps

**Comment by XePeleato** [comment]
It has been proven that this release doesn't work, it doesn't surprise me much, I'll upload a new release today, should it work, the issue will be closed.

**Comment by lukepaulkopera** [comment]
ok thanks :)

**Comment by zenpro1** [comment]
To flash this rom you have the official Android 6.0? or even just the official 5.0.1?
I tried to do the fash but gives me Error Status 7 although he made wipe cache / dalvik chache / system.
What do you suggest?

EDIT: Now it stuck on starting apps

**Comment by XePeleato** [comment]
The rom DOESN'T work, you have been warned by EVERY comment here, I am removing it to prevent further damage.

**Comment by zenpro1** [comment]
Continue to develop the 13 cm on your own or close altogether?

2016-08-14 16:49 GMT+02:00 Eduardo Alonso notifications@github.com:

**Comment by XePeleato** [comment]
I just removed the download

**Comment by zenpro1** [comment]
_How_\* it is going to develop 14 cm for Huawei p8 lite and **when** will be
**released**? *
_I am *_interested*\* in **testing\* *it**.*

Thanks

Il 14 ago 2016 7:20 PM, "Eduardo Alonso" notifications@github.com ha
scritto:

I just removed the download

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
https://github.com/XePeleato/android_device_huawei_p8lite_alel21/issues/12#issuecomment-239685245,
or mute the thread

**Comment by XePeleato** [comment]
@raduvasile20 I don't know I don't have time so it will go slow.

**Comment by powerpaul17** [comment]
Is there something we can help you with? It seemed like it already worked and you solved the RIL problems.

**Comment by XePeleato** [comment]
@powerpaul17 We are talking about CM 14. Of course, if you want to go download Android's source code and work on it, I'll accept your PRs.

**Comment by powerpaul17** [comment]
Oh ok, I thought about getting some release CM 12/13/14/whatever to be useful in a way that it boots and 3G/4G is working :)
