### ISSUE TITLE
Main bugs & things I need help with

### ISSUE THREAD

**Issue by XePeleato** [XePeleato/android_device_huawei_p8lite_alel21#3]
So, in order to keep track of what is fixed and what is not (and if it's fixed, how to fix it), I have created a list, so if anyone wants to collaborate with their experience, any ideas or even linking me to a post or anything, feel free to do so, I'll edit it whenever I achieve something new. The list is small because I want to focus into a small group of issues at a time.

(Currently fighting against):
- Connectivity
- [ ] Wifi
- [ ] Bluetooth
- [ ] NFC
- [x] GSM/3G
- Misc
- [ ] Camera w/Video
- [ ] FM Radio
- [ ] Sound

**Comment by debbiche** [comment]
Does the device currently boot? Any logcat logs?

**Comment by XePeleato** [comment]
Sure it does, I don't know why would you need a logcat, but if you want it anyway, I'll upload it somewhere.

P.S: Just got wifi working
![dsc00178](https://cloud.githubusercontent.com/assets/6912584/13649658/0241047e-e63f-11e5-9ae5-4700b14db594.JPG)

**Comment by debbiche** [comment]
Nice! The reason I was asking is that I'm currently porting CM for the Huawei P8 and was wondering how far you've gotten with the P8 Lite. Mine currently has issues with blobs while booting (stuck at CM boot animation) so I will take a look at what you have done.

**Comment by debbiche** [comment]
@XePeleato Is this list up to date? I got bluetooth and Wifi working yesterday. Sound is still not working. Seems mediaserver dies all the times.

**Comment by XePeleato** [comment]
Oh I forgot about it, if you send me your logcat I might be able to help you

**Comment by debbiche** [comment]
@XePeleato Here you go: http://pastebin.com/EHFKcs2G

**Comment by XePeleato** [comment]
Hm, so you are facing a segmentation error, your best bet is to debug the process in order to detect what's exactly wrong with it

**Comment by debbiche** [comment]
Yeah, what's the best way to debug the process itself?

**Comment by XePeleato** [comment]
For this kind of issue, I'd use gdb. 

Good Luck!

**Comment by debbiche** [comment]
I will try, thanks. What's status for you? What's working and not working?

**Comment by XePeleato** [comment]
The device boots fine as I showed, however when I change some libs to make it more functional, I face some errors

**Comment by debbiche** [comment]
Did you get the audio to work? I had some errors with medaserver and its blobs but I fixed them and everything audio and camera wise seems to load fine but it never completes booting or at best shows the android is upgrading/starting apps screen but no crashes: http://pastebin.com/ztg0X19w

**Comment by XePeleato** [comment]
@debbiche I don't know since I had some issues with media_codecs/profiles.xml 
Could you please find what's the lib that triggers that 'state' ?

**Comment by debbiche** [comment]
Were you able to boot with sound working? I'm not sure which lib causes this state, here is my list (probably a few that are not needed): 
http://pastebin.com/ud57xYeG

**Comment by XePeleato** [comment]
@debbiche As I said above, I haven't tested it, so I guess it's not working. I agree with you, there are some libs that shouldn't be there, altought I am not sure since I haven't finished the rom

**Comment by XePeleato** [comment]
@debbiche I have spotted why it doesn't boot, let me investigate it a little bit more and I'll tell you what is it.

**Comment by debbiche** [comment]
That's great. I cleaned up my blobs list quite a bit but still same effect.
I'm running a new build now since it's been a few days since I did a clean
one.

**Comment by XePeleato** [comment]
The camera is now working!

**Comment by debbiche** [comment]
Very nice. What did you do? Blobs thing? Mine just gives me sensors error
or something.

**Comment by XePeleato** [comment]
Yeah I just copied some blobs and all of a sudden it worked. Audio works in your build right? How did you did it? Have you copied media_codecs.xml or/and media_profiles.xml?

**Comment by debbiche** [comment]
Which blobs did you copy? Audio works perfect for me. Took me a while to
get it to work. And you need all the stuff in etc/audio and some other
files.

**Comment by XePeleato** [comment]
I copied all the libcamera_\* and libjpegenchw.so and libmedia.so (just the 32 bit lib). Is your blob list at your github updated? It'll be easier to know wich ones are missing.

**Comment by debbiche** [comment]
Yeah they are updated and for the audio too so it should work for you.

**Comment by XePeleato** [comment]
Well, since the HuaweiRIL.java I am using is made for Android 5.1 Ther are lots of missing dependencies.
Do We have any Java developer? I can handle C/C++ but not Java.

**Comment by debbiche** [comment]
I do Java but I'm not familiar with how these ril classes work.

**Comment by XePeleato** [comment]
If We had a 5.1 version, it'd be much easier, so whenever Marshmallow is released, I'll switch to it.

**Comment by olrak2** [comment]
There is a 5.1 version available.  But no source.  It's possible to bootup and work with the system with the 5.0 own build kernel and stock 5.1 ramdisk files.

**Comment by XePeleato** [comment]
@olrak2 Oh, could you find me a link? It would be interesting to have a look.

**Comment by olrak2** [comment]
@XePeleato , it's a lot of work. But you can take an nandroid after installation

http://forum.xda-developers.com/p8lite/help/upgrade-android-5-1-1-b008-ale-21-t3285993

First install B052 with mfastboot
Then install B136a with mfastboot
Then install B008 (5.1.1) with dload

**Comment by XePeleato** [comment]
@olrak2 Thank you! I wasn't aware of that.

**Comment by olrak2** [comment]
From my post to haky86: 

If you need them or not, here are all the kernels + ramdisk files:

Download link for kernel android 5.0 ALE-21:
https://mega.nz/#!dF9x1ZbA!pipmYzYtbaKpZbrFPYmAKtmpLaNkszyoLMgyVfsTmZw

Download link for kernel android 5.1.1 ALE-21:
https://mega.nz/#!oRVwxBKI!w2NcBAKouK0Q6aLz-9v01v6evqG8uVFwfCDfnOPFeaI

Download link for kernel android 6.0 ALE-21: https://mega.nz/#!IVdVRSJB!qU4na409x8JCeOFnHoAVjEKEPowl4vY-hbjn5dbQMyw

**Comment by XePeleato** [comment]
@olrak2 It worked! Now I have Android 5.1.1 installed. The server is compiling!

**Comment by olrak2** [comment]
@XePeleato : You can start building 6.0 :smiley: 

https://github.com/olrak2/make_boot_image_hi6210sft
https://github.com/olrak2/android_kernel_huawei_hi6210sft

![screenshot_2016-03-25-11-51-17](https://cloud.githubusercontent.com/assets/17641040/14043915/19588fea-f28a-11e5-8467-2242d95a079a.png)

**Comment by XePeleato** [comment]
@olrak2 Good Job! However, I am now building 5.1.1, the RIL classes compiled perfectly, anyway that are some good news!

**Comment by XePeleato** [comment]
Update: Xposed works

![screenshot_2016-03-26-12-30-43](https://cloud.githubusercontent.com/assets/6912584/14060098/f89d949c-f358-11e5-8608-8437f5e82b2e.png)

**Comment by muhammadfahadbaig** [comment]
@XePeleato didn't Xposed worked flawlessly on AOSP?

**Comment by XePeleato** [comment]
@muhammadfahadbaig Sure it did, but no one got it working on the P8 Lite

**Comment by FelipeBR28** [comment]
Hi, I know this isn't the right place to ask, but... Anyone knows how to unlock bootloader with the new Huawei's website? I don't know and I need it...

**Comment by XePeleato** [comment]
@FelipeBR28 Log in with your Huawei ID here https://emui.huawei.com/en/plugin.php?id=unlock&mod=detail

**Comment by FelipeBR28** [comment]
@XePeleato I know how to, but the problem is that some time ago, you could choose the model number Y300-0000 and then, you had the number, but now you can't even with that, so if there's any other way to do it...

**Comment by olrak2** [comment]
@FelipeBR28 : don't know if it will work but try this unlocking guide

http://huaweip8lite.blogspot.be/  (--> you need google translate :smile: )

**Comment by XePeleato** [comment]
@FelipeBR28 What device do you have?

**Comment by FelipeBR28** [comment]
@olrak2 I'll try it... thanks!!

**Comment by FelipeBR28** [comment]
@XePeleato ALE-L21, the standard

**Comment by muhammadfahadbaig** [comment]
@XePeleato Still no sign of baseband?

**Comment by muhammadfahadbaig** [comment]
There is way to unlock bootloader without Huawei's website. However you must be rooted for that method.

**Comment by XePeleato** [comment]
@muhammadfahadbaig I am working on it.

**Comment by muhammadfahadbaig** [comment]
and also what about graphics.c file? I am working for TWRP for my other Huawei device.

**Comment by XePeleato** [comment]
@debbiche Also asked for it, @muhammadfahadbaig I forgot to upload it
https://gist.github.com/XePeleato/3e886d517fbc7142780d

place it in bootable/recovery/minuitwrp

**Comment by muhammadfahadbaig** [comment]
just one more question... I am compiling TWRP right now. No idea why it's failing at " make: **\* No rule to make target `/datadrive/android/system/out/target/product/hi6210sft/kernel', needed by`/datadrive/android/system/out/target/product/hi6210sft/boot.img'.  Stop. I am using my own prebuilt kernel.
And thanks for graphics.c . You are doing a great job sir!

**Comment by XePeleato** [comment]
@muhammadfahadbaig Thanks! Just copy the kernel to that directory manually, it happened to me too.
`
cp device/HUAWEI/hi6210sft/kernel out/target/product/hi6210sft/kernel`

Change the command as needed.

**Comment by sgspluss** [comment]
First of all thanks @XePeleato for your work on P8 Lite, nice to see there will be an AOSP and maybe CyanogenMod soon. Will follow this project and hope to see an public beta or even an better version soon on XDA :)

**Comment by debbiche** [comment]
@XePeleato Is there anything you did to any makesfiles to get the RIL class to compile except adding the flag to the board config file?

**Comment by XePeleato** [comment]
I had to modify frameworks/opt/telephony/Android.mk However it failed to compile on Android 5.0, I switched to 5.1.1

@sgspluss Just got sound working, whenever RIL works, I'll release a beta.

**Comment by muhammadfahadbaig** [comment]
@XePeleato What you did to fix sound? Added some blobs?

**Comment by muhammadfahadbaig** [comment]
and also @XePeleato , I have cloned your source to my machine so that I can try a build for my p8 lite. I hope if that's ok (any permission or anything)

**Comment by XePeleato** [comment]
@muhammadfahadbaig You can check it in the last commit. Sure, you can clone it and use it however you want, that's why I released it :+1:

**Comment by muhammadfahadbaig** [comment]
@XePeleato Thanks!!! I'm building now...

**Comment by muhammadfahadbaig** [comment]
I have a really bad luck today. Was building on a server, and I have a fixed monthly cap. Didn't knew that I have already used up all of my resources and bam, all servers were shut down. Well, I'll have to wait for a week for the credit to reset :)

**Comment by debbiche** [comment]
@XePeleato  Did you have any issues with camera apps not able to get camera info? I added all the camera blobs but it fails with this error: http://pastebin.com/YMsNAzEy

**Comment by XePeleato** [comment]
@debbiche Does the Camera app work?

**Comment by debbiche** [comment]
@XePeleato No, it just shows a black screen then crashes. I was fixing some other small issues yesterday and managed to get rid of the Camera app exception but it still crashes and force closes. Log with all the errors since boot, starting the camera still causes the invalid id error :
http://pastebin.com/J79zeayE

**Comment by olrak2** [comment]
@XePeleato: Does Bluetooth works on the latest build, the one on XDA?

For me it won't start.  I get an error on startup Android and an error while starting up Bluetooth?

**Comment by XePeleato** [comment]
@olrak2 I forgot to include the BT firmware, I wasn't really focused on it so, my bad. The fix should be really easy, if you want to work on it.

**Comment by gabrielepmattia** [comment]
I'm porting AOSP for Huawei Mate 7 and I managed to get the RIL working by decompiling the original framework and implementing needed functions, try this frameworks/opt/telephony https://github.com/mt7-dev/aosp_frameworks_opt_telephony

**Comment by XePeleato** [comment]
@gabry3795 Cool! I'll check it out, it's nice to have a guy who understands Java by our side.

**Comment by debbiche** [comment]
@gabry3795  That's really amazing! I will run a new MM build for the P8 with this to try it out!

**Comment by gabrielepmattia** [comment]
@XePeleato @debbiche perfect! On Mate7 I can make calls, send and receive sms and 4G but carrier's APN is not set automatically so I have to set it manually to get the 4g internet connection working

**Comment by XePeleato** [comment]
@gabry3795 Tried your files, it throws some Java errors, I'll look further into it

**Comment by gabrielepmattia** [comment]
@XePeleato Post here your make log, maybe I can help! My tree is based on android-6.0.0_r1, which one do you build?

**Comment by XePeleato** [comment]
Oh, I am at 6.0.1 http://pastebin.com/FzbubWrV
I'll try with 6.0.0, I'll also try by extracting the files from the P8 Lite framework.

**Comment by gabrielepmattia** [comment]
It seems that the 8 errors are related only to different android versions and not to my edits.. worse luck I am obliged to build the 6.0 because of the proprietary blobs but now if you can build the 6.0 with my telephony framework you can try to apply my last 3 commits to the original 6.0.1 telephony framework.
As far as regards cyanogenmod I totally give up that project because proprietary libsurfaceflinger and other graphics related blobs has been adapted by huawei so they don't follow the android original code, as a matter of facts if I try to build the 6.0.1 (or cm13) using libsurfaceflinger I get missing methods form libandroid_runtime.so that looks for 6.0.1 methods in a 6.0.0 library. They adapted Android to their libraries instead of adapt their libraries to Android.

**Comment by XePeleato** [comment]
@gabry3795 I am building CM, you don't need surfaceflinger, at least not on the p8 lite. I'll look into it, thanks!

**Comment by XePeleato** [comment]
By the way, I managed to fix it. I'll report the results later on.

**Comment by debbiche** [comment]
@XePeleato Did you get it to work on 6.0.1 or you used 6.0?

**Comment by XePeleato** [comment]
@debbiche I used 6.0.1 but it shouldn't matter

**Comment by Sn0wPaw** [comment]
Hey! I would like to ask is this new release stable enough to use every day? (Sure i know its nightly, but i owned a lot devices, if you know what i mean... ;) )

**Comment by powerpaul17** [comment]
More interestingly: what does it require, is there a boot image? Because I flashed it and it's stuck at the boot screen.

**Comment by FelipeBR28** [comment]
@powerpaul17 did you installed any gapps package? (It doesn't work for me neither :( )

**Comment by XePeleato** [comment]
As you can see there, it's just a nightly, because I enabled my Jenkins instance to compile nightly builds, and whenever I reach a milestone, it's uploaded to github, this one was uploaded as a test, please don't intend to use it as a daily driver. I'll have a look about that, but here you have the boot.img : https://mega.nz/#!ZxwQ2I7K!6EERItMjNbli6aDm2KkaxZfU5iUi74HLaANyiUlYMlU

**Comment by FelipeBR28** [comment]
But...  it's 22 mb... is it flasheable? I mean, if I flash it, I will have CM?

**Comment by XePeleato** [comment]
I'll quote myself "here you have the boot.img" I was answering to @powerpaul17 It's the ""fix"" to the black screen, or at least, that's my best guess, I can't try it at the moment.

**Comment by FelipeBR28** [comment]
@XePeleato Sorry for pissing you, but it stucks for me too, I'll have to flash it after installing the previous zip? Thanks.

**Comment by XePeleato** [comment]
@FelipeBR28 After flashing the zip, you'll have to install that image via fastboot, `fastboot flash boot XXX.img`

**Comment by Sn0wPaw** [comment]
Sorry, can you please link me the "tutorial" for flashing this ROM? I want to do it properly.... thanks

**Comment by XePeleato** [comment]
@Sn0wPaw There's no tutorial because the rom was just uploaded to test if my build script worked, for any issue that you may have, please open a new one so We don't clog this one up.

**Comment by powerpaul17** [comment]
Thanks @XePeleato but even with your boot.img it is stuck at the boot screen. I hope it is not related to a changed vendor partition because I did an upgrade of the Huawei firmware. Can't access it through adb neither, so I can't provide more information now.

**Comment by FelipeBR28** [comment]
@XePeleato I flashed your .img after installing the zip. I left it all night long, and it stucks at "Android is starting. Starting apps." but I connected it to the computer and installed CM drivers.

**Comment by edskv** [comment]
Can someone give me link to download rom?

**Comment by powerpaul17** [comment]
You find it under Code/Releases but it does not work. It was just a build test from XePeleato.

**Comment by edskv** [comment]
Oh right, forgot to check there, thank you :)

**Comment by XePeleato** [comment]
Enough off topic, this is not Xda, this is a developer network

**Comment by noxifoxi** [comment]
@XePeleato  Are all of these bugs fixed?

**Comment by XePeleato** [comment]
@NoxNebula No, it depends on the rom you are talking about but they are not fixed

**Comment by noxifoxi** [comment]
@XePeleato oh ok, I was just wondering because the issue were closed.

Btw, I really love what you are doing here 👍

**Comment by powerpaul17** [comment]
He closed it because people keep asking for his ROM which is really annoying after some time.
