### ISSUE TITLE
I/ServiceManager( 3164): Waiting for service media.audio_policy...

### ISSUE THREAD

**Issue by debbiche** [XePeleato/android_device_huawei_p8lite_alel21#4]
I've been trying to get AOSP booting on the P8 and the booting seems to get stuck here (I have the same blobs as you when it comes to the audio):

I/SystemServer( 3164): Connectivity Service
D/ConnectivityService( 3164): ConnectivityService starting up
D/ConnectivityService( 3164): wifiOnly=false
E/ConnectivityService( 3164): Ignoring protectedNetwork 10
E/ConnectivityService( 3164): Ignoring protectedNetwork 11
E/ConnectivityService( 3164): Ignoring protectedNetwork 12
E/ConnectivityService( 3164): Ignoring protectedNetwork 14
E/ConnectivityService( 3164): Ignoring protectedNetwork 15
I/SystemServer( 3164): Network Service Discovery Service
D/NsdService( 3164): Network service discovery enabled true
I/SystemServer( 3164): UpdateLock Service
I/SystemServiceManager( 3164): Starting com.android.server.notification.NotificationManagerService
I/SystemServiceManager( 3164): Starting com.android.server.storage.DeviceStorageMonitorService
I/SystemServer( 3164): Location Manager
I/SystemServer( 3164): Country Detector
I/SystemServer( 3164): Search Service
I/SystemServer( 3164): DropBox Service
I/SystemServer( 3164): Wallpaper Service
D/WifiHW  ( 3164): wifi_unload_driver
D/WifiHW  ( 3164): enter wifi_load_driver:line:317
W/WallpaperManagerService( 3164): no current wallpaper -- first boot?
I/SystemServer( 3164): Audio Service
E/AudioService( 3164): Media server died.
I/ServiceManager( 3164): Waiting for service media.audio_policy...
W/TelecomManager( 3164): Telecom Service not found.
I/ServiceManager( 3164): Waiting for service media.audio_policy...
I/ServiceManager( 3164): Waiting for service media.audio_policy...
I/ServiceManager( 3164): Waiting for service media.audio_policy...
I/ServiceManager( 3164): Waiting for service media.audio_policy...
W/AudioSystem( 3164): AudioPolicyService not published, waiting...
I/ServiceManager( 3164): Waiting for service media.audio_policy...

Running /bin/mediaserver produces the following error: 
CANNOT LINK EXECUTABLE: could not load library "libaudioflinger.so" needed by "/system/bin/mediaserver"; caused by cannot locate symbol "__android_logPower_print" referenced by "libaudioflinger.so"...

Have you had any similar issues? If yes, how did you solve them. It seems to be cause by a missing function in liblog that the Huawei one has , see here:
http://review.cyanogenmod.org/#/c/99001/

Also tried this without any luck after a clean build: https://github.com/CyanogenMod/android_device_huawei_mt2/tree/cm-12.1/libc_huawei_symbols

Any insight would be appreciated. Thanks.

**Comment by XePeleato** [comment]
Yes, I have faced that issue, I had to disassemble some libs and placed the symbols at 'libc_huawei_symbols'. However you'll need  to edit Android.mk inside bionic/libc in order to read those symbols . I'll upload the line you have to add in a while. You are getting closer!

**Comment by debbiche** [comment]
Thanks a lot for your help! Let me know when you can post/upload it.

**Comment by XePeleato** [comment]
Alright, open bionic/libc/Android.mk and search for "special for arm" there you'll see:

```
LOCAL_NO_CRT_arm := true
LOCAL_CFLAGS_arm += -DCRT_LEGACY_WORKAROUND
LOCAL_SRC_FILES_arm += \
arch-common/bionic/crtbegin_so.c \
arch-arm/bionic/atexit_legacy.c \
arch-common/bionic/crtend_so.S

#Include custom symbols
LOCAL_WHOLE_STATIC_LIBRARIES += $(BOARD_PROVIDES_ADDITIONAL_BIONIC_STATIC_LIBS)

include $(BUILD_SHARED_LIBRARY)
```

Just add
"**LOCAL_WHOLE_STATIC_LIBRARIES += $(BOARD_PROVIDES_ADDITIONAL_BIONIC_STATIC_LIBS)**"
It must look like that, try compiling it again.

Good Luck!

**Comment by debbiche** [comment]
Thanks. Will try soon. Did you do clean build after adding the line or doesn't matter?

EDIT: I assume the line should look like this:
LOCAL_WHOLE_STATIC_LIBRARIES += $(BOARD_RPOVIDES_ADDITIONAL_BIONIC_STATIC_LIBS)

**Comment by XePeleato** [comment]
@debbiche I didn't, it compiles libc automatically since it detects the changes.

**Comment by debbiche** [comment]
hmm added the line as you said but still get this error: 

CANNOT LINK EXECUTABLE: could not load library "libaudioflinger.so" needed by "/system/bin/mediaserver"; caused by cannot locate symbol "__android_logPower_print" referenced by "libaudioflinger.so"...

EDIT:
I just need this line in board config right along with the folder and the added line you described:
BOARD_PROVIDES_ADDITIONAL_BIONIC_STATIC_LIBS += libc_huawei_symbols

I also have libaudioflinger.so as a blob.

**Comment by XePeleato** [comment]
@debbiche Yes, that would be it, are you loading libc as a blob? Is everything updated in your device tree, I'd like to check it.

**Comment by debbiche** [comment]
@XePeleato I'm not loading libc as a blob. I will push my tree now.

@XePeleato : Device tree: https://github.com/debbiche/android_device_huawei_gra_l09

**Comment by debbiche** [comment]
Next missing symbol :)
CANNOT LINK EXECUTABLE: could not load library "libaudiopolicyservice.so" needed by "/system/bin/mediaserver"; caused by cannot locate symbol "_ZN7android11AudioSystem11setFmVolumeEf" referenced by "libaudiopolicyservice.so"...

**Comment by debbiche** [comment]
The phone boots now which is awesome! But bluetooth share goes crazy with FCs hehe

**Comment by VertofChest** [comment]
Shizuku caused this for me. PoS!
